services:
  postgres_db:
    image: postgres:16
    container_name: stock_portfolio_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: uniofgreater2026!@
    ports:
      - "5432:5432"
    volumes:
      - postgres_storage:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  postgres_storage: